// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd6iYeZRdULClr7TvgPgIoEm8hExdvf8c',
    appId: '1:98102202338:web:e69a3fc0aad3df7cd5b3bb',
    messagingSenderId: '98102202338',
    projectId: 'justnotes-prj-justgio',
    authDomain: 'justnotes-prj-justgio.firebaseapp.com',
    storageBucket: 'justnotes-prj-justgio.appspot.com',
    measurementId: 'G-S309CV7CHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPddOJjbiL7ql6tKXFzE4COtc0FPhScsM',
    appId: '1:98102202338:android:e9a9223f965ab3ebd5b3bb',
    messagingSenderId: '98102202338',
    projectId: 'justnotes-prj-justgio',
    storageBucket: 'justnotes-prj-justgio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw_pwHwvCJ5oiBDKX8Ezg8TW7ZuJS6fLI',
    appId: '1:98102202338:ios:61242490c031fd32d5b3bb',
    messagingSenderId: '98102202338',
    projectId: 'justnotes-prj-justgio',
    storageBucket: 'justnotes-prj-justgio.appspot.com',
    iosClientId: '98102202338-f2pcjdfutkgtjkk7vsjfhfhb9g7dcvco.apps.googleusercontent.com',
    iosBundleId: 'io.justg.justnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw_pwHwvCJ5oiBDKX8Ezg8TW7ZuJS6fLI',
    appId: '1:98102202338:ios:61242490c031fd32d5b3bb',
    messagingSenderId: '98102202338',
    projectId: 'justnotes-prj-justgio',
    storageBucket: 'justnotes-prj-justgio.appspot.com',
    iosClientId: '98102202338-f2pcjdfutkgtjkk7vsjfhfhb9g7dcvco.apps.googleusercontent.com',
    iosBundleId: 'io.justg.justnotes',
  );
}
